services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data/
    
volumes:
  postgres-data:
  minio-data: